package pojo;
// Generated 4/03/2016 10:14:53 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DaniosVehiculo generated by hbm2java
 */
public class DaniosVehiculo  implements java.io.Serializable {


     private Integer id;
     private EvaluacionEstadoVehicular evaluacionEstadoVehicular;
     private ParametroEvaluacion parametroEvaluacion;
     private ParteVehiculo parteVehiculo;
     private Date fecha;
     private String evidencia;

    public DaniosVehiculo() {
    }

	
    public DaniosVehiculo(Date fecha) {
        this.fecha = fecha;
    }
    public DaniosVehiculo(EvaluacionEstadoVehicular evaluacionEstadoVehicular, ParametroEvaluacion parametroEvaluacion, ParteVehiculo parteVehiculo, Date fecha, String evidencia) {
       this.evaluacionEstadoVehicular = evaluacionEstadoVehicular;
       this.parametroEvaluacion = parametroEvaluacion;
       this.parteVehiculo = parteVehiculo;
       this.fecha = fecha;
       this.evidencia = evidencia;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EvaluacionEstadoVehicular getEvaluacionEstadoVehicular() {
        return this.evaluacionEstadoVehicular;
    }
    
    public void setEvaluacionEstadoVehicular(EvaluacionEstadoVehicular evaluacionEstadoVehicular) {
        this.evaluacionEstadoVehicular = evaluacionEstadoVehicular;
    }
    public ParametroEvaluacion getParametroEvaluacion() {
        return this.parametroEvaluacion;
    }
    
    public void setParametroEvaluacion(ParametroEvaluacion parametroEvaluacion) {
        this.parametroEvaluacion = parametroEvaluacion;
    }
    public ParteVehiculo getParteVehiculo() {
        return this.parteVehiculo;
    }
    
    public void setParteVehiculo(ParteVehiculo parteVehiculo) {
        this.parteVehiculo = parteVehiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEvidencia() {
        return this.evidencia;
    }
    
    public void setEvidencia(String evidencia) {
        this.evidencia = evidencia;
    }




}


