package pojo;
// Generated 15/01/2016 04:27:27 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EvaluacionEstadoVehicular generated by hbm2java
 */
public class EvaluacionEstadoVehicular  implements java.io.Serializable {


     private Integer id;
     private Propietario propietario;
     private Date fecha;
     private Boolean poseeDanios;
     private Boolean poseeObjetos;
     private Set objetosVehiculoses = new HashSet(0);
     private Set daniosVehiculos = new HashSet(0);

    public EvaluacionEstadoVehicular() {
    }

	
    public EvaluacionEstadoVehicular(Date fecha) {
        this.fecha = fecha;
    }
    public EvaluacionEstadoVehicular(Propietario propietario, Date fecha, Boolean poseeDanios, Boolean poseeObjetos, Set objetosVehiculoses, Set daniosVehiculos) {
       this.propietario = propietario;
       this.fecha = fecha;
       this.poseeDanios = poseeDanios;
       this.poseeObjetos = poseeObjetos;
       this.objetosVehiculoses = objetosVehiculoses;
       this.daniosVehiculos = daniosVehiculos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propietario getPropietario() {
        return this.propietario;
    }
    
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getPoseeDanios() {
        return this.poseeDanios;
    }
    
    public void setPoseeDanios(Boolean poseeDanios) {
        this.poseeDanios = poseeDanios;
    }
    public Boolean getPoseeObjetos() {
        return this.poseeObjetos;
    }
    
    public void setPoseeObjetos(Boolean poseeObjetos) {
        this.poseeObjetos = poseeObjetos;
    }
    public Set getObjetosVehiculoses() {
        return this.objetosVehiculoses;
    }
    
    public void setObjetosVehiculoses(Set objetosVehiculoses) {
        this.objetosVehiculoses = objetosVehiculoses;
    }
    public Set getDaniosVehiculos() {
        return this.daniosVehiculos;
    }
    
    public void setDaniosVehiculos(Set daniosVehiculos) {
        this.daniosVehiculos = daniosVehiculos;
    }




}


