package pojo;
// Generated 7/02/2016 12:30:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Objetos generated by hbm2java
 */
public class Objetos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set objetosVehiculoses = new HashSet(0);

    public Objetos() {
    }

    public Objetos(String nombre, Set objetosVehiculoses) {
       this.nombre = nombre;
       this.objetosVehiculoses = objetosVehiculoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getObjetosVehiculoses() {
        return this.objetosVehiculoses;
    }
    
    public void setObjetosVehiculoses(Set objetosVehiculoses) {
        this.objetosVehiculoses = objetosVehiculoses;
    }




}


