package pojo;
// Generated 7/02/2016 12:30:40 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ObjetosVehiculos generated by hbm2java
 */
public class ObjetosVehiculos  implements java.io.Serializable {


     private Integer id;
     private EvaluacionEstadoVehicular evaluacionEstadoVehicular;
     private Objetos objetos;
     private String descripcion;
     private byte[] evidencia;
     private Date fecha;

    public ObjetosVehiculos() {
    }

	
    public ObjetosVehiculos(Date fecha) {
        this.fecha = fecha;
    }
    public ObjetosVehiculos(EvaluacionEstadoVehicular evaluacionEstadoVehicular, Objetos objetos, String descripcion, byte[] evidencia, Date fecha) {
       this.evaluacionEstadoVehicular = evaluacionEstadoVehicular;
       this.objetos = objetos;
       this.descripcion = descripcion;
       this.evidencia = evidencia;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EvaluacionEstadoVehicular getEvaluacionEstadoVehicular() {
        return this.evaluacionEstadoVehicular;
    }
    
    public void setEvaluacionEstadoVehicular(EvaluacionEstadoVehicular evaluacionEstadoVehicular) {
        this.evaluacionEstadoVehicular = evaluacionEstadoVehicular;
    }
    public Objetos getObjetos() {
        return this.objetos;
    }
    
    public void setObjetos(Objetos objetos) {
        this.objetos = objetos;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte[] getEvidencia() {
        return this.evidencia;
    }
    
    public void setEvidencia(byte[] evidencia) {
        this.evidencia = evidencia;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


